version = 0.1
[y]
[y.deploy]
[y.deploy.parameters]
stack_name = "api-dynamo-new"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1sd0k50un2lnl"
s3_prefix = "api-dynamo-new"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DynamoTable=\"TestTable\""

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "api-dynamo-new"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1sd0k50un2lnl"
s3_prefix = "api-dynamo-new"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DynamoTable=\"TestTable\" FirstTableIndexName=\"GI_one_new\""
