version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "static-cloudfront"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1sd0k50un2lnl"
s3_prefix = "static-cloudfront"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BucketName=\"my-static-html-new\""
